version: '3'

services:
  default:
    image: base:latest
    container_name: base
    volumes:
      - .:/app

  jupyterlab:
    image: base:latest
    container_name: jupyter-lab
    volumes:
      - .:/app
    expose:
      - 8888
    ports:
      - "8888:8888"
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/app/data'
